name: Deploy to PROD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "corona-tracker-backend"
          heroku_email: "corona.tracker.app.jt@gmail.com"
        env:
          HD_DB_CONNECTION: ${{secrets.DB_CONNECTION}}
          HD_SECRET_KEY: ${{secrets.SECRET_KEY}}
          HD_COVID_API_URL: ${{secrets.COVID_API_URL}}
          HD_X_RAPIDAPI_HOST: ${{secrets.X_RAPIDAPI_HOST}}
          HD_X_RAPIDAPI_KEY: ${{secrets.X_RAPIDAPI_KEY}}